//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentesDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASESORIA
    {
        public decimal ID_ASESORIA { get; set; }
        public string TIPO_ASESORIA { get; set; }
        public string PROFESIONAL_RUT { get; set; }
        public string EMPRESA_RUT { get; set; }
        public System.DateTime FECHA_SOLICITUD { get; set; }
        public System.DateTime FECHA_ASESORIA { get; set; }
        public string INFORMACION_RECOPILADA { get; set; }
        public string ESTADO_ASESORIA { get; set; }
        public string DETALLE_ADMINISTRADOR { get; set; }
        public Nullable<System.DateTime> FECHA_CIERRE_ASESORIA { get; set; }
    
        public virtual USUARIO USUARIO { get; set; }
        public virtual EMPRESA EMPRESA { get; set; }
    }
}
