//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentesDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRATO
    {
        public decimal ID_CONTRATO { get; set; }
        public Nullable<System.DateTime> FECHA_CREACION_CONTRATO { get; set; }
        public string EMPRESA_RUT { get; set; }
        public Nullable<System.DateTime> FECHA_TERMINO_CONTRATO { get; set; }
        public string TEXTO_CONTRATO { get; set; }
    }
}
