//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentesDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESA
    {
        public EMPRESA()
        {
            this.ASESORIA = new HashSet<ASESORIA>();
            this.CAPACITACION = new HashSet<CAPACITACION>();
            this.VISITA = new HashSet<VISITA>();
        }
    
        public string RUT { get; set; }
        public string NOMBRE { get; set; }
        public string RUBRO { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<decimal> TELEFONO { get; set; }
        public string MOROSIDAD { get; set; }
    
        public virtual ICollection<ASESORIA> ASESORIA { get; set; }
        public virtual ICollection<CAPACITACION> CAPACITACION { get; set; }
        public virtual ICollection<VISITA> VISITA { get; set; }
    }
}
