//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentesDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public PAGOS()
        {
            this.PLAN_PAGO = new HashSet<PLAN_PAGO>();
        }
    
        public decimal ID_PAGO { get; set; }
        public Nullable<decimal> MONTO { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
    
        public virtual ICollection<PLAN_PAGO> PLAN_PAGO { get; set; }
    }
}
