//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoMasAccidentesDALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIO
    {
        public decimal ID_SERVICIO { get; set; }
        public decimal CANTIDAD { get; set; }
        public string FECHA { get; set; }
        public string DETALLE { get; set; }
    }
}
